const fs = require('fs');
const http = require('http');
const FormData = require('form-data');

const app = http.createServer((req, res) => {
    console.log(`Request: ${req.url}`);
    const form = new FormData();

    // Append two files to the form.
    form.append('file1', fs.readFileSync('./file1.pdf'), {
        filename: 'file1.pdf',
        contentType: 'application/pdf',
        knownLength: fs.statSync('./file1.pdf').size,
    });
    form.append('file2', fs.readFileSync('./file2.pdf'), {
        filename: 'file2.pdf',
        contentType: 'application/pdf',
        knownLength: fs.statSync('./file2.pdf').size,
    });

    // Set headers for multipart response.
    res.writeHead(200, {
        'Content-Type': `multipart/form-data; boundary=${form.getBoundary()}`, // boundary must match the one generated by form-data
        'Content-Length': form.getLengthSync(),
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Allow-Origin': '*', // Update based on your needs (for demo purposes, '*' is more flexible)
    });

    // Write the multipart form data response.
    res.write(form.getBuffer());
    res.end();
});

const port = 4000;
app.listen(port);
console.log(`Server listening on port ${port}`);
